import { DispatchTable } from "@/components/dispatch/DispatchTable";

export default function DispatchLogPage() {
  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="font-display text-lg font-bold uppercase tracking-wide text-slate-100">Dispatch Log</h1>
        <p className="text-sm text-slate-500">
          Every unit dispatch and mitigation action generated by the Action Engine.
        </p>
      </div>

      <DispatchTable />
    </div>
  );
}
